[package]
name = "freemacs"
version = "0.1.0"
edition = "2024"
authors = ["Martin Sandiford"]
license = "GPL-2.0"

[features]
default = []
crossterm = []

[dependencies]
chrono = "0.4.43"
crossterm = "0.29.0"
glob = "0.3.3"
ncurses = "6.0.1"
regex = "1.12.3"
